using MultiCalculator.Database.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace MultiCalculator.Helpers
{
    public class PracticeProblemsHelper
    {
        public static void SendPracticeProblemEmail(UserModel user, string practiceProblem)
        {
            SmtpClient client = new SmtpClient("smtp.gmail.com", 587)
            {
                Credentials = new NetworkCredential("dotnethms.matthewlam@gmail.com", "zixp oqmn wnqy argz"),
                EnableSsl = true,
            };
            MailMessage mail = new MailMessage
            {
                From = new MailAddress("dotnethms.matthewlam@gmail.com"),
                Subject = "Your Generated Practice Problem",
                Body = $"Dear {user.FirstName} {user.LastName},\nThis email is contains the following auto-generated practice problem:\n{practiceProblem}\nKind Regards,\nMDM MultiCalculator\n\nPLEASE DO NOT REPLY. THIS IS AN AUTOGENERATED EMAIL."
            };

            mail.To.Add(user.Email);
            try
            {
                client.Send(mail);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error sending message:" + ex.Message); // Error handling could be more graceful or thorough
            }
        }

        public static string GeneratePracticeProblem()
        {
            // TODO: CALL OpenAIHelper, method: SubmitAndGetApiResponse(string prompt, UserModel sendingUser) to generate question and then return it.
            var practiceProblem = "";
			return practiceProblem;
        }
    }
}
