using MultiCalculator.Database.Models;
using MultiCalculator.Database.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace MultiCalculator.Helpers
{
    public class PracticeProblemsHelper
    {
        readonly IDatabaseService _databaseService;

        public PracticeProblemsHelper(IDatabaseService databaseService)
        {
            _databaseService = databaseService;
        }

        public void SendPracticeProblemEmail(UserModel user, string practiceProblem, string email = null)
        {
            SmtpClient client = new SmtpClient("smtp.gmail.com", 587)
            {
                Credentials = new NetworkCredential("dotnethms.matthewlam@gmail.com", "zixp oqmm wnqy argz"),
                EnableSsl = true,
            };
            MailMessage mail = new MailMessage
            {
                From = new MailAddress("dotnethms.matthewlam@gmail.com"),
                Subject = "Your Generated Practice Problem",
                Body = $"Dear {user.FirstName} {user.LastName},\nThis email is contains the following auto-generated practice problem:\n{practiceProblem}\nKind Regards,\nMDM MultiCalculator\n\nPLEASE DO NOT REPLY. THIS IS AN AUTOGENERATED EMAIL."
            };

            mail.To.Add(email ?? user.Email);
            try
            {
                client.Send(mail);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error sending message:" + ex.Message); // Error handling could be more graceful or thorough
            }
        }

        public (string, string) GeneratePracticeProblem()
        {
            var allPreviousQuestions = _databaseService.LoadAllCalculationHistory();
            var random = new Random();
            var randomNumber = random.Next(0, allPreviousQuestions.Count);
			return (allPreviousQuestions[randomNumber].Question, allPreviousQuestions[randomNumber].Answer);
        }

        public List<(string, string)> GenerateNAmountOfPracticeProblems(int numberOfProblems)
        {
            var allPreviousQuestions = _databaseService.LoadAllCalculationHistory();
            var random = new Random();
            var practiceProblems = new List<(string, string)>();
            for (int i = 0; i < numberOfProblems; i++)
            {
                var randomNumber = random.Next(0, allPreviousQuestions.Count);
                practiceProblems.Add((allPreviousQuestions[randomNumber].Question, allPreviousQuestions[randomNumber].Answer));
            }
            return practiceProblems;
        }
    }
}
