using MultiCalculator.Database.Models;
using MultiCalculator.Database.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace MultiCalculator.Helpers
{
    public class PracticeProblemsHelper
    {
        readonly IDatabaseService _databaseService;

        public PracticeProblemsHelper(IDatabaseService databaseService)
        {
            _databaseService = databaseService;
        }

        public void SendPracticeProblemEmail(UserModel user, string practiceProblem, string? email = null)
        {
            SmtpClient client = new SmtpClient("smtp.gmail.com", 587)
            {
                Credentials = new NetworkCredential("dotnethms.matthewlam@gmail.com", "zixp oqmm wnqy argz"),
                EnableSsl = true,
            };
            MailMessage mail = new MailMessage
            {
                From = new MailAddress("dotnethms.matthewlam@gmail.com"),
                Subject = "Your Generated Practice Problem",
                Body = GenerateDynamicEmailBody(user, practiceProblem),
                IsBodyHtml = true
            };

            mail.To.Add(email ?? user.Email);
            try
            {
                client.Send(mail);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error sending message:" + ex.Message);
            }
        }

        public (string, string) GeneratePracticeProblem()
        {
            var allPreviousQuestions = _databaseService.LoadAllCalculationHistory();
            var random = new Random();
            var randomNumber = random.Next(0, allPreviousQuestions.Count);
			return (allPreviousQuestions[randomNumber].Question, allPreviousQuestions[randomNumber].Answer);
        }

        public List<(string, string)> GenerateNAmountOfPracticeProblems(int numberOfProblems)
        {
            var allPreviousQuestions = _databaseService.LoadAllCalculationHistory();
            var random = new Random();
            var practiceProblems = new List<(string, string)>();
            for (int i = 0; i < numberOfProblems; i++)
            {
                var randomNumber = random.Next(0, allPreviousQuestions.Count);
                practiceProblems.Add((allPreviousQuestions[randomNumber].Question, allPreviousQuestions[randomNumber].Answer));
            }
            return practiceProblems;
        }

		private string GenerateDynamicEmailBody(UserModel user, string practiceProblem)
		{
			return $@"
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }}
        .email-container {{
            max-width: 600px;
            margin: 20px auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }}
        .header {{
            background-color: #007bff;
            color: #ffffff;
            padding: 10px 20px;
            border-radius: 10px 10px 0 0;
            text-align: center;
        }}
        .content {{
            padding: 20px;
            line-height: 1.6;
        }}
        .content p {{
            margin: 10px 0;
        }}
        .footer {{
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #777777;
        }}
        .footer strong {{
            color: #333333;
        }}
    </style>
</head>
<body>
    <div class='email-container'>
        <div class='header'>
            <h1>MDM Calculator</h1>
        </div>
        <div class='content'>
            <p>Dear {user.FirstName} {user.LastName},</p>
            <p>This email is contains the following auto-generated practice problem:</p>
            <blockquote>{practiceProblem}</blockquote>
            <p>Kind Regards,</p>
            <p><strong>MDM Calculator Team</strong></p>
        </div>
        <div class='footer'>
            <p><strong>PLEASE DO NOT REPLY.</strong> THIS IS AN AUTOGENERATED EMAIL.</p>
        </div>
    </div>
</body>
</html>";
		}
	}
}
